[package]
name = "miden-client"
version = "0.3.0"
description = "Client library that facilitates interaction with the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-client"
documentation = "https://docs.rs/miden-client/0.3.0"
keywords = ["miden", "client"]
edition = "2021"
rust-version = "1.78"
default-run = "miden"

[lib]
crate-type = ["lib"]

[[bin]]
name = "miden"
path = "src/main.rs"

[[test]]
name = "integration"
path = "tests/integration/main.rs"
required-features = ["integration"]

[features]
concurrent = ["miden-lib/concurrent", "miden-objects/concurrent", "miden-tx/concurrent"]
default = ["std"]
integration = ["testing", "concurrent", "uuid"]
std = ["miden-objects/std"]
testing = ["miden-objects/testing", "miden-lib/testing"]
test_utils = ["miden-objects/testing"]
wasm = ["async-std", "getrandom", "tonic"]

[dependencies]
async-std = { version = "1.12.0", optional = true }
async-trait = { version = "0.1" }
futures = { version = "0.3" }
hex = { version = "0.4" }
miden-lib = { version = "0.3", default-features = false }
miden-tx = { version = "0.3", default-features = false }
miden-objects = { version = "0.3", default-features = false, features = ["std", "serde"] }
prost = { version = "0.12.3" }
rand = { version = "0.8.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
thiserror = { version = "1.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
uuid = { version = "1.6.1", features = ["serde", "v4"], optional = true }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.3", features = ["derive"] }
comfy-table = "7.1.0"
figment = { version = "0.10", features = ["toml", "env"] }
lazy_static = "1.4.0"
miden-node-proto = { version = "0.3", default-features = false }
rusqlite = { version = "0.30.0", features = ["vtab", "array", "bundled"] }
rusqlite_migration = { version = "1.0" }
tokio = { version = "1.29", features = ["rt-multi-thread", "net", "macros"] }
tonic = { version = "0.11" }
toml = { version = "0.8" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
async-std = { version = "1.12.0", optional = true }
futures = { version = "0.3" }
getrandom = { version = "0.2", features = ["js"], optional = true }
tonic = { version="0.11.0", default-features = false, features=["prost","codegen"], optional = true }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["console"] }

[dev-dependencies]
# needed for tests to run always with the test utils feature
miden_client = { package = "miden-client", path = ".", features = [
    "test_utils",
    "uuid",
] }
