[package]
name = "miden-client"
version = "0.2.0"
description = "Client library that facilitates interaction with the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-client"
documentation = "https://docs.rs/miden-client/0.2.0"
keywords = ["miden", "client"]
edition = "2021"
rust-version = "1.75"
default-run = "miden-client"

[[test]]
name = "integration"
path = "tests/integration/main.rs"
required-features = ["integration"]

[features]
concurrent = [
    "miden-lib/concurrent",
    "miden-objects/concurrent",
    "miden-tx/concurrent",
]
default = ["std"]
integration = ["testing", "concurrent", "uuid"]
std = ["miden-objects/std"]
testing = ["miden-objects/testing", "miden-lib/testing"]
test_utils = ["miden-objects/testing"]

[dependencies]
async-trait = { version = "0.1" }
clap = { version = "4.3", features = ["derive"] }
comfy-table = "7.1.0"
figment = { version = "0.10", features = ["toml", "env"] }
lazy_static = "1.4.0"
miden-lib = { path="../../miden-base/miden-lib", default-features = false }
miden-node-proto = { version = "0.2", default-features = false }
miden-tx = { path="../../miden-base/miden-tx", default-features = false }
miden-objects = { path="../../miden-base/objects", features = ["serde"] }
rand = { version = "0.8.5" }
rusqlite = { version = "0.30.0", features = ["bundled"] }
rusqlite_migration = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
tokio = { version = "1.29", features = ["rt-multi-thread", "net", "macros"] }
tonic = { version = "0.11" }
toml = { version = "0.8" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
uuid = { version = "1.6.1", features = ["serde", "v4"], optional = true }
web-sys = { version = "0.3", features = ["console"] }

[dev-dependencies]
# needed for tests to run always with the test utils feature
miden_client = { package = "miden-client", path = ".", features = [
    "test_utils",
    "uuid",
] }
