import type { Metadata } from "next";
import { Inter } from "next/font/google";
// base css file
import 'swiper/css';
import '@/assets/css/scrollbar.css';
import '@/assets/css/globals.css';
import '@/assets/css/range-slider.css';
import Sidebar from "@/layouts/dashboard/_sidebar";
import { ThemeProvider } from "next-themes";
import { Header } from "@/layouts/dashboard/_dashboard";
import { WasmProvider } from "@/context/wasm-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>{
      <div className="bg-light-100 dark:bg-dark-100 flex min-h-screen flex-col">
        {/* <WasmProvider> */}
          <div className="xl:pl-72 2xl:pl-80">
            <Header />
            <main className="mb-12 flex flex-grow flex-col pt-16 sm:pt-24">
              <ThemeProvider
                attribute="class"
                enableSystem={false}
                defaultTheme="dark"
              >
                <Header />
                <Sidebar className="hidden xl:block" />
                <main className={
                  'min-h-[100vh] px-4 pt-16 pb-16 sm:px-6 sm:pb-20 lg:px-8 xl:px-10 xl:pb-24 3xl:px-12'
                }
                >
                  {children}
                </main>
              </ThemeProvider>
            </main>
          </div>
        {/* </WasmProvider> */}
      </div>
    }</body>
    </html>
  );
}

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning={true}>
//       <body className={inter.className}>{
//       <div style={{ display: 'flex' }}>
//         <ThemeProvider
//           attribute="class"
//           enableSystem={false}
//           defaultTheme="dark"
//         >
//           <Header />
//           <Sidebar />
//           <main className={
//             'min-h-[100vh] px-4 pt-24 pb-16 sm:px-6 sm:pb-20 lg:px-8 xl:px-10 xl:pb-24 3xl:px-12'
//           }
//           >
//             {children}
//           </main>
//         </ThemeProvider>
//       </div>
//     }</body>
//     </html>
//   );
// }
