[package]
name = "miden-wasm"
version = "1.0.0"
description = "WebAssembly based toolkit for developing zero knowledge applications with Polygon Miden"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[features]
concurrent = ["miden-lib/concurrent", "miden-objects/concurrent", "miden-tx/concurrent"]
default = ["std"]
std = ["miden-objects/std"]
testing = ["miden-objects/testing", "miden-lib/testing"]
test_utils = ["miden-objects/testing"]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
futures = "0.3"
getrandom = { version = "0.2", features = ["js"] }
hex = { version = "0.4" }
miden-client = { path = "../../demox-miden-client", version = "0.3.0", default-features = false, features = ["wasm", "async"] }
<<<<<<< HEAD
miden-lib = { version = "0.3.1", default-features = false, features = ["testing"] }
miden-tx = { version = "0.3.1", default-features = false, features = ["async"] }
miden-objects = { version = "0.3.1", default-features = false, features = ["std", "serde", "testing"] }
=======
miden-lib = { path="../../miden-base-copy/miden-lib", default-features = false }
miden-tx = { path="../../miden-base-copy/miden-tx", default-features = false, features = ["async"] }
miden-objects = { version = "0.3.1", default-features = false, features = ["serde"] }
>>>>>>> a58f985 (miden website 0.3)
prost = { version = "0.12.3" }
rand = { version = "0.8.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6.5"
tonic = { version="0.11.0", default-features = false, features=["prost","codegen"] }
tonic-web-wasm-client = "0.5"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["console"] }
console_error_panic_hook = "0.1.6"

[build-dependencies]
tonic-build = { version="0.11.0", default-features = false, features = ["prost"]}

